# Generated by Django 5.1.4 on 2024-12-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_for', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject_teachers',
            field=models.ManyToManyField(related_name='subject_classes', to='users.teacher'),
        ),
    ]
