# Generated by Django 5.1.4 on 2024-12-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
