# Generated by Django 5.1.4 on 2025-01-01 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_initial'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_client', models.DateTimeField(help_text='Client date and time')),
                ('date_time_db', models.DateTimeField(auto_now_add=True, help_text='Server date and time')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.teacher')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'indexes': [models.Index(fields=['student', 'date_time_client'], name='attendance__student_c012e0_idx'), models.Index(fields=['teacher', 'date_time_client'], name='attendance__teacher_7076ab_idx'), models.Index(fields=['class_instance', 'date_time_client'], name='attendance__class_i_126b70_idx')],
                'unique_together': {('student', 'class_instance', 'date_time_client')},
            },
        ),
    ]
